routes/web.php
<?php

use App\Http\Controllers\ComputersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaticController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [StaticController::class, 'index'])->name('home.index');
Route::get('/about', [StaticController::class, 'about'])->name('home.about');
Route::get('/contact', [StaticController::class, 'contact'])->name('home.contact');
Route::resource('computers', ComputersController::class);

Route::get('/store/{category?}/{product?}', function ($category = null, $product = null) {
    if (isset($category)){
        if (isset($product)){
            return "<h1 style='color: red'>{$product}</h1>";
        }
        return "<h1 style='color: red'>{$category}</h1>";
    }
    else{
        return '<h1>STORE</h1>';
    }
});

/*
Route::get('/store', function () {
    $select = request('style');
    if (isset($select)){
        return "<h1>This page is viewing <span style='color: blue'>". strip_tags($select)."</span></h1>";
    }
    else{
        return "<h1>This page is viewing <span style='color: blue'>All Products</span></h1>";
    }
    
});
*/

app/Models/Computer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Computer extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ComputersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Computer;
class ComputersController extends Controller
{
    // private static function getData(){
    //     return [
    //         ['id'=> 1, 'name' => 'LG', 'origin' => 'Koria'] ,
    //         ['id'=> 2, 'name' => 'Siemens', 'origin' => 'Germmany'] ,
    //         ['id'=> 3, 'name' => 'HP', 'origin' => 'USA'],
    //         ['id'=> 4, 'name' => 'Leneovo', 'origin' => 'Denmmark']
    //     ];
    // }


    public function index() {
        return view('computers.index', [
            'computers' =>  Computer::all()
        ]);
    }

    
    public function create() {
       return view('computers.create');
    }

    public function store(Request $request) {

        $request-> validate([
            'computer-name' => 'required',
            'computer-origin' => 'required',
            'computer-price' => ['required', 'integer']
        ]);
        $computer = new Computer();
        $computer->name  = strip_tags($request-> input('computer-name'));
        $computer->origin  = strip_tags($request-> input('computer-origin'));
        $computer->price  = strip_tags($request-> input('computer-price'));

        $computer->save();

        return redirect()->route('computers.index');
    }

   
    public function show($computer) {
        return view(
        'computers.show',
        [
            'computer' => Computer::findOrFail($computer)
        ]);
    }

    
    public function edit($computer) {
        return view(
            'computers.edit',
            [
            'computer' => Computer::findOrFail($computer)
        ]);
    }

    
    public function update(Request $request, $computer) {
        $request-> validate([
            'computer-name' => 'required',
            'computer-origin' => 'required',
            'computer-price' => ['required', 'integer']
        ]);
        $to_update = Computer::findOrFail($computer);

        $to_update->name  = strip_tags($request-> input('computer-name'));
        $to_update->origin  = strip_tags($request-> input('computer-origin'));
        $to_update->price  = strip_tags($request-> input('computer-price'));

        $to_update->save();

        return redirect()->route('computers.show', $computer);
    }

    
    public function destroy($computer) {

        $to_delete = Computer::findOrFail($computer);
        $to_delete -> delete();
        return redirect()->route('computers.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StaticController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StaticController extends Controller
{
    public function index () {
        return view('welcome');
    }
    public function about () {
        return view('about');
    }
    public function contact () {
        return view('contact');
    }
}

resources/views/about.blade.php
@extends('layout')
@section('title', 'About')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center pt-8">
            <h1>ABOUT US</h1>
        </div>
        <div class="mt-8">
            <h4>This is the About page</h4>
        </div>
    </div>
@endsection

resources/views/computers/create.blade.php
@extends('layout')
@section('title', 'Create Computers')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center pt-8">
            <h1>Create a new Computer</h1>
        </div>
        <div class="flex justify-center">
            <form class="smooth" action="{{route('computers.store')}}" method="post">
                @csrf
                <div>
                    <label for="computer-name">Computer Name</label>
                    <input value="{{old('computer-name')}}" type="text" name="computer-name" id="computer-name">
                    @error('computer-name')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>


                <div>
                    <label for="computer-origin">Computer Origin</label>
                    <input value="{{old('computer-origin')}}" type="text" name="computer-origin" id="computer-origin" >
                    @error('computer-origin')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>


                <div>
                    <label for="computer-price">Computer Price</label>
                    <input value="{{old('computer-price')}}" type="text" name="computer-price" id="computer-price">
                    @error('computer-price')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/computers/edit.blade.php
@extends('layout')
@section('title', 'Edit Computers')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center pt-8">
            <h1>Edit an old Computer</h1>
        </div>
        <div class="flex justify-center">
            <form class="smooth" action="{{route('computers.update', ['computer' => $computer->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div>
                    <label for="computer-name">Computer Name</label>
                    <input value="{{$computer -> name}}" type="text" name="computer-name" id="computer-name">
                    @error('computer-name')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>


                <div>
                    <label for="computer-origin">Computer Origin</label>
                    <input value="{{$computer->origin}}" type="text" name="computer-origin" id="computer-origin" >
                    @error('computer-origin')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>


                <div>
                    <label for="computer-price">Computer Price</label>
                    <input value="{{$computer->price}}" type="text" name="computer-price" id="computer-price">
                    @error('computer-price')
                        <div class="form-error">
                            {{$message}}
                        </div>
                    @enderror
                </div>
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/computers/index.blade.php
@extends('layout')
@section('title', 'Computers')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center ">
            <h1>COMPUTERS</h1>
        </div>
        <div class="mt-8">
            @if (count($computers) > 0)
                <ul>
                    @foreach ($computers as $computer)
                        <a href="{{ route('computers.show', ['computer' => $computer['id']]) }}">
                            <li>{{$computer['name']}} made in ({{$computer['origin']}})-<strong>{{$computer['price']}}$</strong></li>
                        </a>
                    @endforeach
                </ul>
                @else
                    <p>There are no Computers to display</p>
            @endif
        </div>
    </div>
@endsection

resources/views/computers/show.blade.php
@extends('layout')
@section('title', 'Show Computers')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center pt-8">
            <h1>COMPUTERS</h1>
        </div>
        <div class="mt-8">
            <h3>{{$computer['name']}} ({{$computer['origin']}}) - <strong>{{$computer['price']}}$</strong></h3>
        </div>
        <a class="edit-btn" href="{{ route('computers.edit', $computer->id) }}">Edit</a>
    
        <form method="POST" action="{{ route('computers.destroy', $computer->id) }}">
            @csrf
            @method('DELETE')
            <input class="delete-btn" value="Delete" type="submit">
        </form>
    </div>
@endsection

resources/views/contact.blade.php
@extends('layout')
@section('title', 'Contact')

@section('content')
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="flex justify-center pt-8">
            <h1>CONTACT US</h1>
        </div>
        <div class="mt-8">
            <h4>This is the Contact page</h4>
        </div>
    </div>
@endsection